{"name": "test_correct_login[-liuhaotao1015]", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range", "trace": "self = <allure_pytest.listener.AllureListener object at 0x0000016AFF19FAC8>, item = <Function test_correct_login[-liuhaotao1015]>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_setup(self, item):\n        if not self._cache.get(item.nodeid):\n            uuid = self._cache.push(item.nodeid)\n            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())\n            self.allure_logger.schedule_test(uuid, test_result)\n    \n        yield\n    \n        uuid = self._cache.get(item.nodeid)\n        test_result = self.allure_logger.get_test(uuid)\n        for fixturedef in _test_fixtures(item):\n            group_uuid = self._cache.get(fixturedef)\n            if not group_uuid:\n                group_uuid = self._cache.push(fixturedef)\n                group = TestResultContainer(uuid=group_uuid)\n                self.allure_logger.start_group(group_uuid, group)\n            self.allure_logger.update_group(group_uuid, children=uuid)\n        params = item.callspec.params if hasattr(item, 'callspec') else {}\n    \n>       test_result.name = allure_name(item, params)\n\n..\\..\\..\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_pytest\\listener.py:88: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nitem = <Function test_correct_login[-liuhaotao1015]>, parameters = {'pwd': 'liuhaotao1015', 'user': ''}\n\n    def allure_name(item, parameters):\n        name = escape_name(item.name)\n        title = allure_title(item)\n>       return title.format(**{**parameters, **item.funcargs}) if title else name\nE       IndexError: tuple index out of range\n\n..\\..\\..\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_pytest\\utils.py:111: IndexError"}, "start": 1617875369239, "stop": 1617875369239, "uuid": "552c5fd8-d00c-4828-932e-f8a36f4bebc3", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "用例1：{}"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-BN9QCCJ"}, {"name": "thread", "value": "19444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}], "links": [{"type": "test_case", "url": "https://mail.qq.com/", "name": "qq邮箱"}]}