{"name": "# 错误的账号", "status": "passed", "description": "错误的账号", "attachments": [{"name": "log", "source": "498a3fc3-396a-4155-b6c2-be57ef39e607-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4dd5eaf2-4669-4272-b886-33ace1681d9e-attachment.txt", "type": "text/plain"}], "start": 1618312446672, "stop": 1618312451041, "uuid": "8430a700-7150-435f-b810-ce4be8983108", "historyId": "883a541f97fe6c8c9ddfd4c2f0cae9b6", "testCaseId": "60c800e0ac0825f582650298f219264b", "fullName": "script.test_login.Test_login#test_error_account", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "用例2：错误的账号"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-BN9QCCJ"}, {"name": "thread", "value": "1964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}], "links": [{"type": "test_case", "url": "https://mail.qq.com/", "name": "qq邮箱"}]}