{"name": "#正确的账号、错误的密码、正确的验证码", "status": "passed", "description": "错误的账号", "attachments": [{"name": "log", "source": "ddd2fb9b-59ee-446d-84a6-5701c51d9eb3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2d22b3e4-eb69-4388-a377-e41d2b2af548-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "037ff275-5803-459a-9bca-94bc81f3a830-attachment.txt", "type": "text/plain"}], "start": 1618313711348, "stop": 1618313715821, "uuid": "f048e7f6-f817-4680-9464-3d572737da06", "historyId": "883a541f97fe6c8c9ddfd4c2f0cae9b6", "testCaseId": "60c800e0ac0825f582650298f219264b", "fullName": "script.test_login.Test_login#test_error_account", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "用例2：正确的账号、错误的密码、正确的验证码"}, {"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-BN9QCCJ"}, {"name": "thread", "value": "15192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}], "links": [{"type": "test_case", "url": "https://mail.qq.com/", "name": "qq邮箱"}]}